### ISSUE TITLE
Adding Contributors image on The README.md

### ISSUE THREAD

**Issue by ark0078** [AmateursLeague/sneaky-package#85] opened 2024-10-06 11:32 UTC
Can you please assign me this issue so that I can add Contributors image??
 @this-is-yaash @Wahid7852

**Comment by ShashwatAgrawal20** [comment] 2024-10-06 12:06
@ark0078 hey, this doesn't add any actual value to the project, one can also see the contributors on the contributors side on the project itself, there's no need to clutter the README.

There are bunch of peeps opening the same issue please do something which actually adds value to the project.

duplicate of #75 #66

**Closed by ShashwatAgrawal20** 2024-10-06 12:06 UTC
Labels: duplicate, invalid, wontfix
